version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: "postgresql://postgres:Ja1000413026@localhost:5432/postgres?schema=public"
    depends_on:
      - db
    volumes:
      - ./prisma:/app/prisma

  frontend:
    build: ./frontend
    image: electiva2_clontinder_jaac_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata: