services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

  backend:
    build: .
    image: electiva2_clontinder_jaac_backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/mydb?schema=public"
      JWT_SECRET: "853a31fc905a7f791bc9fa0fd5e36776c48c1aca19f14fd2e33cef8053f3339b"
      PORT: 3000
    depends_on:
      db:
        condition: service_healthy   # Espera a que Postgres esté listo
    volumes:
      - ./prisma:/app/prisma
    restart: always

  frontend:
    build: ./frontend
    image: electiva2_clontinder_jaac_frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: "http://localhost:3000"
    restart: always

volumes:
  pgdata:
