version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    image: electiva2_clontinder_jaac_backend
    ports:
      - "3001:3001"
    environment:
      # 👇 Usa el nombre del servicio "db" en lugar de localhost
      DATABASE_URL: "postgresql://user:password@db:5432/mydb?schema=public"
    depends_on:
      - db
    volumes:
      - ./prisma:/app/prisma

  frontend:
    build: ./frontend
    image: electiva2_clontinder_jaac_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      # 👇 si usas React con variables, define la URL del backend
      REACT_APP_API_URL: "http://localhost:3001"

volumes:
  pgdata:
